### ISSUE TITLE
Build failure "Can't make a derived instance of 'Traversible (EnumMap k)'".

### ISSUE THREAD

**Issue by jimstutt** [michalt/enummapset#8]
[2 of 5] Compiling Data.EnumMap.Base ( Data/EnumMap/Base.hs, dist/dist-sandbox-62e6f0ad/build/Data/EnumMap/Base.o )

Data/EnumMap/Base.hs:180:49:
    Can't make a derived instance of ‘Traversable (EnumMap k)’
      (even with cunning newtype deriving):
      You need DeriveTraversable to derive an instance for this class
    In the newtype declaration for ‘EnumMap’
cabal: Error: some packages failed to install:
enummapset-0.5.2.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by michalt** [comment]
This should be fixed by d2603aad165ea90542504a13fc40cbdc4b3959a8

Please reopen if you still have problems.
